### ISSUE TITLE
Using Client_connection.create

### ISSUE THREAD

**Issue by arsalan0c** [anmonteiro/ocaml-h2#155]
Hi. Thank you for creating H2.

I am not sure if I am misunderstanding but it seems that although `Client_connection.create` has `config` and `push_handler` as optional parameters, their arguments must be provided in addition to `error_handler`. This is because `error_handler` is a labelled and final parameter. 

If this is the case, adding a final unit parameter can allow the function to be called without the need for providing the optional arguments.

Here's the full type of `Client_connection.create`:
```OCaml
?config:Config.t ->
    ?push_handler:(Request.t ->
                   (Client_connection.response_handler, unit) result) ->
    error_handler:Client_connection.error_handler -> Client_connection.t
```

**Comment by anmonteiro** [comment]
`Client_connection` isn't really meant to be used directly, but rather through one of the runtimes. What's your use case?

Note you can always create a client by passing `?config:None`, etc

**Comment by arsalan0c** [comment]
> `Client_connection` isn't really meant to be used directly, but rather through one of the runtimes. What's your use case?
> 
> Note you can always create a client by passing `?config:None`, etc

I see, thanks!

**Comment by anmonteiro** [comment]
I'm going to close this one. Let me know if you have any other questions.
