### ISSUE TITLE
OCaml 5.0.0 Seeded Hash Compatibility

### ISSUE THREAD

**Issue by patricoferris** [anmonteiro/ocaml-h2#167]
Thanks for the great library !

A recent upstream change (https://github.com/ocaml/ocaml/pull/11157) in the compiler to `Hashtbl.SeededHashedType` means `ocaml-h2` no longer builds on 5.0.0. I have a fix on top of the vendored version of `ocaml-h2` for `dream` https://github.com/patricoferris/ocaml-h2/commit/fb8722096170cdebfcec59252ce330c317d29d63 (I think that will also keep it working on `< 5`).

cc: @aantron

**Comment by patricoferris** [comment]
Actually `let seeded_hash...` will need to suppress `warning 32 [unused-value-declaration]` for older compilers.

**Comment by anmonteiro** [comment]
Feel free to submit a PR!
