### ISSUE TITLE
The generated documentation in README is outdated

### ISSUE THREAD

**Issue by daleiz** [anmonteiro/ocaml-h2#176]
[the doc](https://anmonteiro.com/ocaml-h2/) is still 0.5.0, and maybe we could link the doc [here](https://ocaml.org/p/h2/0.8.0/doc/index.html).

**Comment by anmonteiro** [comment]
That's a good idea. Do you know how the documentation can end up published in that page?

**Comment by daleiz** [comment]
I'm not familiar with the ocaml ecosystem, but it seems that you just need to release a new version of the package and it will automatically show the corresponding documentation there.
