### ISSUE TITLE
h2.opam: Add constraint on hpack version

### ISSUE THREAD

**Issue by reynir** [anmonteiro/ocaml-h2#213]
In h2.opam we depend on hpack without any constraints. I suspect this is likely usually fine as the interface hasn't changed at all.
https://github.com/anmonteiro/ocaml-h2/blob/9f9f29d95b6278cfecc7a0cd60ddcfde15bf3dc5/h2.opam#L20

However, due to a behavior in opam-monorepo (https://github.com/tarides/opam-monorepo/issues/331) this lack of constraint makes opam-monorepo choose the wrong version: https://github.com/mirage/mirage/pull/1411#issuecomment-1477702239

To work around the behavior in opam-monorepo we could add a constraint `"hpack" {= version}` in h2.opam.

**Comment by anmonteiro** [comment]
Not opposed to it. Wanna send a PR?
