### ISSUE TITLE
Handling of "authority" pseudo-header

### ISSUE THREAD

**Issue by hannesm** [anmonteiro/ocaml-h2#216]
Somehow, I get into trouble when requesting api.github.com.

The request I send (pretty-printed using Request.pp_hum)

```
main.exe: [DEBUG] Sending ((method "GET") (target "/") (scheme "https") (headers 
                          (("user-agent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.134 Safari/537.36")
                          (":authority" "api.github.com")("accept" "*/*"))))
```

This leads to a `PROTOCOL_ERROR (0x1)` (without any further information).

Now, if instead I send no authority:

```
main.exe: [DEBUG] Sending ((method "GET") (target "/") (scheme "https") (headers 
                          (("user-agent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.134 Safari/537.36")
                          ("accept" "*/*"))))
```

(so, removing the ":authority" header), I get a reply with status 400

With a Host header (like in the HTTP/1 times):

```
main.exe: [DEBUG] Sending ((method "GET") (target "/") (scheme "https") (headers 
                          (("user-agent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.134 Safari/537.36")
                          ("host" "api.github.com")("accept" "*/*"))))
```

I get a good reply (status code 200 and some json).

And I noticed in your code "(* TODO: `:authority` pseudo-header? *)` (in request.ml) -- where I wonder whether this is still planned?

When using curl, I can see that any `-H "Host: foo.com"` is translated into a `:authority: foo.com` header. I fail to understand what this `authority` is all about, and how to properly communicate it with your h2 stack?

**Comment by anmonteiro** [comment]
I can reproduce this in h2, but not in Piaf. Taking a look

**Comment by anmonteiro** [comment]
Regarding the `:authority` pseudo-header, it's the HTTP/2 replacement for `Host`: https://httpwg.org/specs/rfc9113.html#rfc.section.8.3.1

**Comment by anmonteiro** [comment]
Regarding the `PROTOCOL_ERROR`, the protocol contemplates sending a reason string along with the error, but GitHub's HTTP/2 implementation sends an empty string.

**Comment by anmonteiro** [comment]
@hannesm OK I figured it out.

This is very confusing, and we should fix it in h2, indeed.

- The pseudo-headers (those starting with `:` need to be serialized before any normal headers). 
- `H2.Headers.t` keeps a rev-list of headers (we inherited this from http/af, trying to stay compatible)


### Actionable for you

While this isn't fixed in h2, you want to make sure that you're sending `:authority` before any regular headers

**Comment by hannesm** [comment]
thanks for your investigation. I pushed https://github.com/roburio/http-lwt-client/pull/20 which makes the header ordering more strict.

I'm a bit surprised by the API of h2 that it is so easy to do requests that are invalid according to the spec).

**Comment by hannesm** [comment]
So I have a workaround in place. Closing.
