### ISSUE TITLE
New release of h2 packages 

### ISSUE THREAD

**Issue by tmcgilchrist** [anmonteiro/ocaml-h2#227]
@anmonteiro Would it be possible to get a new h2-eio release that includes the eio v0.12 and gluten-eio changes?
I've created a PR to update the changelog https://github.com/anmonteiro/ocaml-h2/pull/226. 

Depends on https://github.com/anmonteiro/gluten/issues/72.

**Comment by anmonteiro** [comment]
fixed c694398c1b429db622638e94f9a6f8fbce2a208a

https://github.com/anmonteiro/ocaml-h2/releases/tag/0.11.0

https://github.com/ocaml/opam-repository/pull/24687
