### ISSUE TITLE
Richer SSL support?

### ISSUE THREAD

**Issue by hansole** [anmonteiro/ocaml-h2#233]
Hi,

I'm using ocaml-grpc, which uses h2 and gluten. H2 and gluten have support for using SSL, but it is quite limited in what is supported. You can only provide a certificate and a key (for the server side). ocaml-ssl which is a wrapper aound OpenSSL (libssl) creates a context, that can add additional certificates. It also allows for using SSL context on both the client and server side, for mutual authentication. 

I have made a simple patch that allows the context to be created outside h2, and given as argument when creating a connection, instead of certificate and key.

https://github.com/hansole/gluten/tree/ssl-context
https://github.com/hansole/ocaml-h2/tree/ssl-context

Would it be possible to provide this kind of functionality as part of the libraries?

Not sure how hard it will be to support a common interface, that supports both SSL and TLS. I have not looked much at TLS.

**Comment by anmonteiro** [comment]
this is a common misconception that I haven't done enough to address. It's pretty easy to use your own SSL context from the outside without any changes to gluten or this library. Check the ALPN code in this repo for an example: https://github.com/anmonteiro/ocaml-h2/blob/master/examples/alpn/unix/alpn_server_ssl.ml

**Comment by hansole** [comment]
Thanks for the explanation. I'll change my code to use this approach.
