### ISSUE TITLE
How to compile examples

### ISSUE THREAD

**Issue by reynir** [anmonteiro/ocaml-h2#234]
I am trying to compile the examples, and I am unsuccessful. I am mainly interested in compiling the lwt client example. I can deduce it requires a development version of httpaf, so I pinned httpaf with `--dev-repo`. However, it still fails with unbound value `Reqd.response_with_upgrade`. Can you tell me what version of httpaf I need to pin?

https://github.com/anmonteiro/ocaml-h2/blob/a0e3f4506528bf31e0f32f272c688662436af366/examples/lwt/lwt_h2c.ml#L115

I would also recommend adding this information to the opam file as a dev dependency.

**Comment by anmonteiro** [comment]
Hey @reynir, you should pin the packages in https://github.com/anmonteiro/httpaf to get upgrade support and compile the examples successfully.

As for opam: I don't use it, so I'll defer to your judgement on the best way to track that in the opam files.

**Comment by reynir** [comment]
A note in a README file would do, too.

**Comment by anmonteiro** [comment]
This should be fixed now that httpun has been released to opam and h2 depends on `httpun-types`.
