### ISSUE TITLE
Body reader on_read includes empty END_STREAM DATA frame in the last buffer

### ISSUE THREAD

**Issue by adamchol** [anmonteiro/ocaml-h2#253]
While working with ocaml-grpc I encountered a weird bug where the last packet of my stream crashed my server. Upon further investigation i noticed that the last buffer in [on_read](https://github.com/anmonteiro/ocaml-h2/blob/49c0591ce90e54187625919a460b694c8f3d003b/lib/h2.mli#L330C1-L335C1) includes an empty DATA with END_STREAM flag set. It seems to actually follow the spec but should it really get there? What's the rationale? Feel free to close this issue, I just found it a bit odd.

cosigned @wokalski

**Comment by anmonteiro** [comment]
why was this closed? did you work around it? is this no longer an issue?

**Comment by wokalski** [comment]
A brainfart
