### ISSUE TITLE
Invalid HTTP response sent

### ISSUE THREAD

**Issue by iams-wu** [anmonteiro/ocaml-h2#52]
Just did a fresh install with ocaml 4.07. Tried the sample server in README on both windows and linux and got the same error:

ERR_INVALID_HTTP_RESPONSE

The `GET match does not even trigger.

**Comment by anmonteiro** [comment]
@iams-wu I'd like to help but there isn't enough information in this ticket to understand what's going on. How are you issuing a request to the server you just built?

**Comment by anmonteiro** [comment]
@iams-wu I'm going to need more information in order to take a look at your problem. This issue is at risk of being closed within the next week if that's not the case.
