### ISSUE TITLE
Trailing headers

### ISSUE THREAD

**Issue by entropitor** [anmonteiro/ocaml-h2#97]
It seems impossible to use this library to sent

HEADERS frame
DATA frame
HEADERS frame

This is something that would be needed to implement GRPC for ocaml (https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)

**Comment by anmonteiro** [comment]
Trailer headers are still not supported, but the infrastructure to add them exists.

There's some initial work towards supporting them in https://github.com/anmonteiro/ocaml-h2/pull/72, but there hasn't been further interest so far.

Happy to kick around some ideas and design an API, even if naive at first (Ideally we would only allow sending trailer headers after we've sent a response first).
